In [1]:
import torch
import difftorch

def f_rosenbrock(x):
  x, y = x[0], x[1]
  return (1. - x)**2 + 100. * (y - x**2)**2

def f_spherical_cartesian(x):
    r, theta, phi = x[0], x[1], x[2]
    x, y, z = r*phi.sin()*theta.cos(), r*phi.sin()*theta.sin(), r*phi.cos()
    return torch.stack([x, y, z])
    
# grad
# Gradient of vector-to-scalar function f, evaluated at x
x = torch.randn(2)
g = difftorch.grad(f_rosenbrock, x)
print(x, g)

# gradv
# Gradient-vector product (directional derivative) of vector-to-scalar function f, evaluated at x, with vector v
x, v = torch.randn(2), torch.randn(2)
gv = difftorch.gradv(f_rosenbrock, x, v)
print(x, v, gv)

# jacobian
# Jacobian of vector-to-vector function f, evaluated at x
x = torch.randn(3)
j = difftorch.jacobian(f_spherical_cartesian, x)
print(x, j)

# jacobianv
# Jacobian-vector product of vector-to-vector function f, evaluated at x, with vector v
x, v = torch.randn(3), torch.randn(3)
jv = difftorch.jacobianv(f_spherical_cartesian, x, v)
print(x, v, jv)

# jacobianTv
# Transposed-Jacobian-vector (vector-Jacobian) product of vector-to-vector function f, evaluated at x, with vector v
x, v = torch.randn(3), torch.randn(3)
jv = difftorch.jacobianTv(f_spherical_cartesian, x, v)
print(x, v, jv)

# hessianv
# Hessian-vector product of vector-to-scalar function f, evaluated at x, with vector v
x, v = torch.randn(2), torch.randn(2)
hv = difftorch.hessianv(f_rosenbrock, x, v)
print(x, v, hv)

# hessian
# Hessian of vector-to-scalar function f, evaluated at x
x = torch.randn(2)
h = difftorch.hessian(f_rosenbrock, x)
print(x, h)

# laplacian
# Laplacian of vector-to-scalar function f, evaluated at x
x = torch.randn(2)
l = difftorch.laplacian(f_rosenbrock, x)
print(x, l)

# curl
# Curl of vector-to-vector function f, evaluated at x
x = torch.randn(3)
c = difftorch.curl(f_spherical_cartesian, x)
print(x, c)

# div
# Divergence of vector-to-vector function f, evaluated at x
x = torch.randn(3)
d = difftorch.div(f_spherical_cartesian, x)
print(x, d)

tensor([-0.8188, -0.0538]) tensor([-240.8413, -144.8447])
tensor([ 0.1584, -0.6201]) tensor([-0.4763,  0.5831]) tensor(-93.9090)
tensor([ 1.3047, -1.4277, -1.4153]) tensor([[-0.1409, -1.2758,  0.0288],
        [ 0.9778, -0.1838, -0.2000],
        [ 0.1549,  0.0000,  1.2890]])
tensor([ 1.6378, -0.6959,  0.0437]) tensor([ 0.5056, -0.7171,  0.4605]) tensor([ 0.5623, -0.5366,  0.4722])
tensor([-1.4456,  0.6751,  0.4212]) tensor([-0.6579, -1.7092, -0.1816]) tensor([-0.8124,  0.5455,  1.9796])
tensor([-1.0438, -1.1759]) tensor([-0.0039, -0.5578]) tensor([-239.8811, -113.1937])
tensor([ 1.1183, -1.1105]) tensor([[1946.8594, -447.3128],
        [-447.3128,  200.0000]])
tensor([1.5431, 2.2523]) tensor(2158.6287)
tensor([-0.0451, -1.2066, -0.3227]) tensor([-0.0399, -0.9636,  0.2829])
tensor([ 0.4569, -0.7173,  0.7276]) tensor(0.4263)
